### ISSUE TITLE
Backend is serverless BUT Frontend is not

### ISSUE THREAD

**Issue by abdennour** [patrick-michelberger/serverless-shop#2]
What about deploying also the frontend to S3 , I mean copy files of "public/*" to S3 Bucket. 

Please look at this [tuto](https://medium.com/@omgwtfmarc/deploying-create-react-app-to-s3-or-cloudfront-48dae4ce0af) , then update "serverless.yml" accordingly

**Comment by patrick-michelberger** [comment]
Hi @abdennour,

thanks for your feedback. The current implementation uses Firebase Hosting - Google's equivalent to S3 static webpage hosting - as described in the accompanying blog post.

```
# Deploy the app e.g. via Firebase
$ npm install -g firebase-tools
$ firebase login
$ firebase init
# You will need to agree with database.rules.json being created, choose build as the public directory, and also agree to Configure as a single-page app by replying with y.
# Create a production build
$ yarn run build
# Deploy the app
$ firebase deploy
```

Of course, you could easily substitute it with S3, if you feel more comfortable with AWS.
