### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by kosirm** [patrick-michelberger/serverless-shop#3]
Thank you for this project and tutorial on Medium, I think it is a great example! Is there ANY chance that you will upgrade this project with "multiple products, categories etc"?

**Comment by patrick-michelberger** [comment]
Hi @kosirm, maybe in the late summer. I'm currently busy with another project. However, feel free to contribute!

**Comment by kosirm** [comment]
Thanks!

**Comment by jtomaszon** [comment]
Do you have any update on this amazing project?
